### ISSUE TITLE
Быстрая смена версии php внутри box

### ISSUE THREAD

**Issue by eugenezadorin** [whiskyjs/box#4]
Появилась идея сделать команду для переключения версии php-cli.

Что-то вроде 

sites php use 7.2

И под капотом в общем-то простая перелинковка /usr/bin/php на нужный бинарник.

**Comment by whiskyjs** [comment]
Для этого уже есть update-alternatives

`sudo update-alternatives --set php /usr/bin/php7.3`

Нужен ли нам ещё один алиас?

**Comment by eugenezadorin** [comment]
Не знал о существовании этой штуки - в итоге линковал у себя вручную :-)

Значит алиас не нужен - но в readme было бы хорошо упомянуть. Я сделаю PR

**Comment by eugenezadorin** [comment]
#5

**Comment by whiskyjs** [comment]
Принял.
